apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: stakater-logging-es
  namespace: logging
spec:
  releaseName: stakater-logging-es
  chart:
    repository: https://raw.githubusercontent.com/upmc-enterprises/elasticsearch-operator/master/charts
    name: elasticsearch
    version: 0.1.5
  values:
    # Default values for elasticsearch-operator.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.
    image:
      repository: stakater/elasticsearch-kubernetes
      tag: 6.2.4
      pullPolicy: IfNotPresent

    clientReplicas: 1
    # change to ONE master to avoid split brain issue & unassigned shards issue
    # hoping for this to get fixed: https://github.com/upmc-enterprises/elasticsearch-operator/issues/105
    masterReplicas: 1
    dataReplicas: 2
    dataVolumeSize: 20Gi
    javaOpts: "-Xms1024m -Xmx1024m" # they must be in synch with resources block

    # Deploy data nodes across zones
    # zones:
    # - "Central US"
    # - "East US"
      
    # Enable ssl or not
    use-ssl: false

    snapshot:
      enabled: false
      bucketName: elasticsnapshots
      schedule: "@every 2m"
      image: upmcenterprises/elasticsearch-cron:0.0.4
      authentication:
        enabled: false
        password: test
        username: test

    storage:
    # If class is set, then the other storage fields will not be used.
      class: ssd
      # e.g. gp2 for AWS
      type: REPLACE_STORAGE_TYPE
      # e.g. kubernetes.io/aws-ebs for AWS
      classProvisioner: kubernetes.io/REPLACE_PROVISIONER
      # Retain or Delete
      reclaimPolicy: Delete

    kibana:
      enabled: false
      image: docker.elastic.co/kibana/kibana-oss:6.1.3

    cerebro:
      enabled: false
      image: upmcenterprises/cerebro:0.6.8

    statsd:
      enabled: false
      host: ""

    resources: # they must be in synch with java-options setting above!
      requests:
        memory: 1024Mi
        cpu: 500m
      limits:
        memory: 1536Mi
        cpu: '1'
