apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: stakater-logging-es-operator
  namespace: logging
spec:
  releaseName: stakater-logging-es-operator
  chart:
    repository: https://raw.githubusercontent.com/upmc-enterprises/elasticsearch-operator/master/charts
    name: elasticsearch-operator
    version: 0.1.3
  values:
    image:
      repository: upmcenterprises/elasticsearch-operator
      tag: 0.0.12
      pullPolicy: Always
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    rbac:
      enabled: true