apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: stakater-logging-kibana
  namespace: logging
spec:
  releaseName: stakater-logging-kibana
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: kibana
    version: 1.1.1
  values:
    image:
      tag: "6.2.4"
    files:
      kibana.yml:
        server.name: kibana
        server.host: "0"
        server.port: 5601
        elasticsearch.url: "http://elasticsearch-stakater-logging-es-cluster.logging:9200"
    deployment:
      annotations:
        authproxy.stakater.com/enabled: "true"
        authproxy.stakater.com/upstream-url: "http://127.0.0.1:5601"
        authproxy.stakater.com/source-service-name: stakater-logging-kibana
        authproxy.stakater.com/redirection-url: "https://kibana.REPLACE_NAMESPACE.REPLACE_DOMAIN_NAME"
        authproxy.stakater.com/listen: "0.0.0.0:80"
    service:
      externalPort: 80
      annotations:
        config.xposer.stakater.com/Domain: REPLACE_DOMAIN_NAME
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-{{.Namespace}}'
        config.xposer.stakater.com/IngressURLTemplate: 'kibana.{{.Namespace}}.{{.Domain}}'
        xposer.stakater.com/annotations: |-
          kubernetes.io/ingress.class: internal-ingress
          ingress.kubernetes.io/rewrite-target: /
          ingress.kubernetes.io/force-ssl-redirect: true
          forecastle.stakater.com/expose: true
          forecastle.stakater.com/icon: https://github.com/stakater/ForecastleIcons/raw/master/kibana.png
          forecastle.stakater.com/appName: Kibana
      labels:
        expose: "true"
